CRITICAL - 2022-12-09 22:03:35 --> Call to undefined function form_open()
in APPPATH\Views\login.php on line 53.
 1 SYSTEMPATH\View\View.php(213): include()
 2 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('login', [], true)
 4 APPPATH\Controllers\Auth.php(16): view('login')
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->login()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-09 22:04:32 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'tokoonline_01'@'localhost' (using password: YES) in C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'tokoonline_01', 'ronald123', 'toko_online', 3306, '', 0)
#1 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\BaseModel.php(659): CodeIgniter\Model->insert(Object(App\Entities\User), false)
#8 C:\xampp\htdocs\toko\app\Controllers\Auth.php(37): CodeIgniter\BaseModel->save(Object(App\Entities\User))
#9 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->register()
#10 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\toko\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\BaseModel.php(659): CodeIgniter\Model->insert(Object(App\Entities\User), false)
#7 C:\xampp\htdocs\toko\app\Controllers\Auth.php(37): CodeIgniter\BaseModel->save(Object(App\Entities\User))
#8 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->register()
#9 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\toko\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2022-12-09 22:04:32 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`username`, `salt`, `password`, `created_by`, `created_date`) VALUES (:username:, :salt:, :password:, :created_by:, :created_date:)', [...], false)
 3 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(659): CodeIgniter\Model->insert(Object(App\Entities\User), false)
 7 APPPATH\Controllers\Auth.php(37): CodeIgniter\BaseModel->save(Object(App\Entities\User))
 8 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->register()
 9 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
10 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-09 22:06:00 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'tokoonline_01'@'localhost' (using password: YES) in C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'tokoonline_01', 'ronald123', 'toko_online', 3306, '', 0)
#1 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\BaseModel.php(659): CodeIgniter\Model->insert(Object(App\Entities\User), false)
#8 C:\xampp\htdocs\toko\app\Controllers\Auth.php(37): CodeIgniter\BaseModel->save(Object(App\Entities\User))
#9 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->register()
#10 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\toko\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\BaseModel.php(659): CodeIgniter\Model->insert(Object(App\Entities\User), false)
#7 C:\xampp\htdocs\toko\app\Controllers\Auth.php(37): CodeIgniter\BaseModel->save(Object(App\Entities\User))
#8 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->register()
#9 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\toko\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2022-12-09 22:06:00 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`username`, `salt`, `password`, `created_by`, `created_date`) VALUES (:username:, :salt:, :password:, :created_by:, :created_date:)', [...], false)
 3 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(659): CodeIgniter\Model->insert(Object(App\Entities\User), false)
 7 APPPATH\Controllers\Auth.php(37): CodeIgniter\BaseModel->save(Object(App\Entities\User))
 8 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->register()
 9 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
10 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-09 22:08:48 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'tokoonline_01'@'localhost' (using password: YES) in C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'tokoonline_01', 'ronald123', 'toko_online', 3306, '', 0)
#1 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\BaseModel.php(659): CodeIgniter\Model->insert(Object(App\Entities\User), false)
#8 C:\xampp\htdocs\toko\app\Controllers\Auth.php(37): CodeIgniter\BaseModel->save(Object(App\Entities\User))
#9 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->register()
#10 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\toko\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\BaseModel.php(659): CodeIgniter\Model->insert(Object(App\Entities\User), false)
#7 C:\xampp\htdocs\toko\app\Controllers\Auth.php(37): CodeIgniter\BaseModel->save(Object(App\Entities\User))
#8 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->register()
#9 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\toko\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2022-12-09 22:08:48 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`username`, `salt`, `password`, `created_by`, `created_date`) VALUES (:username:, :salt:, :password:, :created_by:, :created_date:)', [...], false)
 3 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(659): CodeIgniter\Model->insert(Object(App\Entities\User), false)
 7 APPPATH\Controllers\Auth.php(37): CodeIgniter\BaseModel->save(Object(App\Entities\User))
 8 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->register()
 9 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
10 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-09 22:09:08 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'tokoonline_01'@'localhost' (using password: YES) in C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'tokoonline_01', 'ronald123', 'toko_online', 3306, '', 0)
#1 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\BaseModel.php(659): CodeIgniter\Model->insert(Object(App\Entities\User), false)
#8 C:\xampp\htdocs\toko\app\Controllers\Auth.php(37): CodeIgniter\BaseModel->save(Object(App\Entities\User))
#9 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->register()
#10 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\toko\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\BaseModel.php(659): CodeIgniter\Model->insert(Object(App\Entities\User), false)
#7 C:\xampp\htdocs\toko\app\Controllers\Auth.php(37): CodeIgniter\BaseModel->save(Object(App\Entities\User))
#8 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->register()
#9 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\toko\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2022-12-09 22:09:08 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`username`, `salt`, `password`, `created_by`, `created_date`) VALUES (:username:, :salt:, :password:, :created_by:, :created_date:)', [...], false)
 3 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(659): CodeIgniter\Model->insert(Object(App\Entities\User), false)
 7 APPPATH\Controllers\Auth.php(37): CodeIgniter\BaseModel->save(Object(App\Entities\User))
 8 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->register()
 9 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
10 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-09 22:09:16 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'tokoonline_01'@'localhost' (using password: YES) in C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'tokoonline_01', 'ronald123', 'toko_online', 3306, '', 0)
#1 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\BaseModel.php(659): CodeIgniter\Model->insert(Object(App\Entities\User), false)
#8 C:\xampp\htdocs\toko\app\Controllers\Auth.php(37): CodeIgniter\BaseModel->save(Object(App\Entities\User))
#9 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->register()
#10 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\toko\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\BaseModel.php(659): CodeIgniter\Model->insert(Object(App\Entities\User), false)
#7 C:\xampp\htdocs\toko\app\Controllers\Auth.php(37): CodeIgniter\BaseModel->save(Object(App\Entities\User))
#8 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->register()
#9 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\toko\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2022-12-09 22:09:16 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`username`, `salt`, `password`, `created_by`, `created_date`) VALUES (:username:, :salt:, :password:, :created_by:, :created_date:)', [...], false)
 3 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(659): CodeIgniter\Model->insert(Object(App\Entities\User), false)
 7 APPPATH\Controllers\Auth.php(37): CodeIgniter\BaseModel->save(Object(App\Entities\User))
 8 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->register()
 9 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
10 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-09 22:10:51 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'tokoonline_01'@'localhost' (using password: YES) in C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'tokoonline_01', 'ronald123', 'toko_online', 3306, '', 0)
#1 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\BaseModel.php(659): CodeIgniter\Model->insert(Object(App\Entities\User), false)
#8 C:\xampp\htdocs\toko\app\Controllers\Auth.php(37): CodeIgniter\BaseModel->save(Object(App\Entities\User))
#9 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->register()
#10 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\toko\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\BaseModel.php(659): CodeIgniter\Model->insert(Object(App\Entities\User), false)
#7 C:\xampp\htdocs\toko\app\Controllers\Auth.php(37): CodeIgniter\BaseModel->save(Object(App\Entities\User))
#8 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->register()
#9 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\toko\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2022-12-09 22:10:51 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`username`, `salt`, `password`, `created_by`, `created_date`) VALUES (:username:, :salt:, :password:, :created_by:, :created_date:)', [...], false)
 3 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(659): CodeIgniter\Model->insert(Object(App\Entities\User), false)
 7 APPPATH\Controllers\Auth.php(37): CodeIgniter\BaseModel->save(Object(App\Entities\User))
 8 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->register()
 9 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
10 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-09 22:11:31 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'tokoonline_01'@'localhost' (using password: YES) in C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'tokoonline_01', 'ronald123', 'toko_online', 3306, '', 0)
#1 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\BaseModel.php(659): CodeIgniter\Model->insert(Object(App\Entities\User), false)
#8 C:\xampp\htdocs\toko\app\Controllers\Auth.php(37): CodeIgniter\BaseModel->save(Object(App\Entities\User))
#9 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->register()
#10 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\toko\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\BaseModel.php(659): CodeIgniter\Model->insert(Object(App\Entities\User), false)
#7 C:\xampp\htdocs\toko\app\Controllers\Auth.php(37): CodeIgniter\BaseModel->save(Object(App\Entities\User))
#8 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->register()
#9 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\toko\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\toko\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2022-12-09 22:11:31 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`username`, `salt`, `password`, `created_by`, `created_date`) VALUES (:username:, :salt:, :password:, :created_by:, :created_date:)', [...], false)
 3 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(659): CodeIgniter\Model->insert(Object(App\Entities\User), false)
 7 APPPATH\Controllers\Auth.php(37): CodeIgniter\BaseModel->save(Object(App\Entities\User))
 8 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->register()
 9 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
10 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
